import {
  BellIcon,
  ChatIcon,
  FaqIcon,
  HomeIcon,
  ProfileIcon,
  ReportsIcon,
  ReviewsIcon,
  ReputationIcon,
  AutomationIcon,
  IntegrationIcon,
  SubscriptionsIcon,
  TasksIcon,
} from './icons';

export const portalSearchItems = Object.freeze([
  {
    id: 'dashboard',
    title: 'Главная',
    description: 'Доска, показатели, рейтинг и рабочие блоки',
    route: '/dashboard',
    permission: 'dashboard.view',
    group: 'Навигация',
    Icon: HomeIcon,
    keywords: ['главная', 'доска', 'дашборд', 'dashboard', 'показатели', 'аналитика'],
  },
  {
    id: 'reviews',
    title: 'Отзывы',
    description: 'SLA, AI-ответы, согласование и юридическая эскалация',
    route: '/reviews',
    permission: 'reviews.view',
    group: 'Навигация',
    Icon: ReviewsIcon,
    keywords: ['отзывы', 'репутация', 'яндекс', '2gis', 'ozon', 'wb', 'отзовик', 'sla', 'ai', 'негатив'],
  },
  {
    id: 'reputation',
    title: 'Репутация',
    description: 'Причины изменений, площадки, SLA и рекомендации',
    route: '/reputation',
    permission: 'reputation.view',
    group: 'Навигация',
    Icon: ReputationIcon,
    keywords: ['репутация', 'аналитика', 'причины', 'негатив', 'рейтинг', 'insights', 'sla'],
  },
  {
    id: 'automations',
    title: 'Автоматизации',
    description: 'Правила реакции на отзывы, SLA и согласования',
    route: '/automations',
    permission: 'automations.view',
    group: 'Навигация',
    Icon: AutomationIcon,
    keywords: ['автоматизации', 'правила', 'сценарии', 'триггеры', 'sla', 'задачи'],
  },
  {
    id: 'integrations',
    title: 'Интеграции',
    description: 'Подключения, синхронизация, диагностика и provider status',
    route: '/integrations',
    permission: 'integrations.view',
    group: 'Навигация',
    Icon: IntegrationIcon,
    keywords: ['интеграции', 'яндекс', '2gis', 'ozon', 'wb', 'wildberries', 'отзовик', 'provider', 'sync', 'синхронизация'],
  },
  {
    id: 'subscriptions',
    title: 'Подписки',
    description: 'Тариф, лимиты, пакеты и история платежей',
    route: '/subscriptions',
    permission: 'billing.view',
    group: 'Навигация',
    Icon: SubscriptionsIcon,
    keywords: ['подписка', 'тариф', 'оплата', 'лимиты', 'пакеты'],
  },
  {
    id: 'reports',
    title: 'Отчёты',
    description: 'Список, конструктор и расписание отчётов',
    route: '/reports',
    permission: 'reports.view',
    group: 'Навигация',
    Icon: ReportsIcon,
    keywords: ['отчеты', 'отчёты', 'аналитика', 'pdf', 'конструктор', 'расписание'],
  },
  {
    id: 'tasks',
    title: 'Задачи',
    description: 'Kanban, список, приоритеты и сроки',
    route: '/tasks',
    permission: 'tasks.view',
    group: 'Навигация',
    Icon: TasksIcon,
    keywords: ['задачи', 'kanban', 'канбан', 'чеклист', 'приоритет'],
  },
  {
    id: 'profile',
    title: 'Профиль',
    description: 'Личные данные пользователя',
    route: '/profile',
    group: 'Профиль',
    Icon: ProfileIcon,
    keywords: ['профиль', 'личные данные', 'аккаунт', 'пользователь'],
  },
  {
    id: 'company',
    title: 'Компания',
    description: 'Реквизиты и данные организации',
    route: '/profile?tab=company',
    permission: 'company.view',
    group: 'Профиль',
    Icon: ProfileIcon,
    keywords: ['компания', 'инн', 'огрн', 'организация', 'реквизиты'],
  },
  {
    id: 'security',
    title: 'Безопасность',
    description: 'PIN-код и активные сессии',
    route: '/profile?tab=security',
    group: 'Профиль',
    Icon: ProfileIcon,
    keywords: ['безопасность', 'pin', 'пин', 'сессии', 'пароль'],
  },
  {
    id: 'users',
    title: 'Пользователи',
    description: 'Команда, роли и доступы',
    route: '/profile?tab=users',
    permission: 'team.view',
    group: 'Профиль',
    Icon: ProfileIcon,
    keywords: ['пользователи', 'команда', 'роли', 'доступ', 'пригласить'],
  },
  {
    id: 'notifications',
    title: 'Уведомления',
    description: 'События и настройки уведомлений',
    route: '/notifications',
    group: 'Сервисы',
    Icon: BellIcon,
    keywords: ['уведомления', 'колокольчик', 'события', 'push', 'telegram'],
  },
  {
    id: 'faq',
    title: 'FAQ',
    description: 'Ответы на частые вопросы',
    route: '/faq',
    permission: 'support.view',
    group: 'Поддержка',
    Icon: FaqIcon,
    keywords: ['faq', 'помощь', 'вопросы', 'ответы', 'инструкция'],
  },
  {
    id: 'manager-chat',
    title: 'Персональный менеджер',
    description: 'Стратегия, тариф, отчёты и развитие',
    route: '/chat?channel=manager',
    permission: 'support.view',
    group: 'Поддержка',
    Icon: ChatIcon,
    keywords: ['менеджер', 'чат', 'стратегия', 'поддержка'],
  },
  {
    id: 'technical-chat',
    title: 'Техническая поддержка',
    description: 'Ошибки, вход, интеграции и работа кабинета',
    route: '/chat?channel=technical',
    permission: 'support.view',
    group: 'Поддержка',
    Icon: ChatIcon,
    keywords: ['техподдержка', 'техническая', 'ошибка', 'баг', 'интеграция', 'вход'],
  },
]);
